import './globals.css'
import Nav from './components/navgationbar/page'

export const metadata = {
  title: 'ASH-Foundation',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}